repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        additional_dependencies: [toml]
        language_version: python3
